import React, { Component } from "react";

export const episodes = [
  {
    episode: "1",
    name: "2020 Outlook: Travel Recovery Trends to Watch",
    description: (
      <>
        <p>
          In 2020, many frequent travelers found themselves grounded far longer
          than they ever expected, due to the coronavirus pandemic. When
          travelers increasingly take to the skies again, how can they approach
          their travels more responsibly and sustainably? <br />
          <br />
          In this episode, Bruce Poon Tip, founder of G Adventures and author of
          Looptail: How One Company Changed the World by Reinventing Business
          and UNLEARN: The Year the Earth Stood Still, discusses his reflections
          on 2020 and how the travel industry can bounce back with a greater
          focus on sustainability and responsible travel.
        </p>
      </>
    ),
    embedUrl: "93hQquGY4fs",
    link: "/episodes/2020-outlook-travel-recovery-trends-to-watch/",
    time: "Available Now",
    date: "June 4, 2020",
    cta: "View Details",
    tags: "Data and Trends",
    title: <>Exploring the Future of Travel with G Adventures</>,
    speakers: "",
  },
  {
    episode: "2",
    name: "How Travel Systems are Adapting to COVID-19",
    description: "asdf",
    embedUrl: "lEy5UakXXmI",
    link: "/episodes/How-Travel-System-are-Adapting-to-COVID-19/",
    time: "Available Now",
    date: "July 27, 2020",
    cta: "View Details",
    tags: "Innovation",
    title: <>Exploring the Future of Travel with G Adventures</>,
    speakers: "",
  },
  {
    episode: "3",
    name: "What’s Next for Business Travel?",
    description: "asdf",
    embedUrl: "1mam8X5N_l0",
    link: "/episodes/Whats-Next-for-Business-Travel/",
    time: "Available Now",
    date: "August 19, 2020",
    cta: "View Details",
    tags: "Retailing, Innovation",
    title: <>Exploring the Future of Travel with G Adventures</>,
    speakers: "",
  },
  {
    episode: "4",
    name: "What’s Really on the Dark Web?",
    description: "asdf",
    embedUrl: "laZMBVj9ZbM",
    link: "/episodes/Whats-Really-on-the-Dark-Web/",
    time: "Available Now",
    date: "September 17, 2020",
    cta: "View Details",
    tags: "Data and Trends",
    title: <>Exploring the Future of Travel with G Adventures</>,
    speakers: "",
  },
  {
    episode: "5",
    name: "Travel Recovery Trends to Watch in Fall 2020",
    description: "asdf",
    embedUrl: "oN1LocEIPVg",
    link: "/episodes/Travel-Recovery-Trends-to-Watch-in-Fall-2020/",
    time: "Available Now",
    date: "October 14, 2020",
    cta: "View Details",
    tags: "Data and Trends",
    title: <>Exploring the Future of Travel with G Adventures</>,
    speakers: "",
  },
  {
    episode: "6",
    name: "Enhancing the Traveler Experience in Every Channel",
    description: "asdf",
    embedUrl: "uE9RtodEpSc",
    link: "/episodes/Enhancing-the-Traveler-Experience-in-Every-Channel/",
    time: "Available Now",
    date: "Nov 18, 2020",
    cta: "View Details",
    tags: "Retailing, Innovation",
    title: <>Exploring the Future of Travel with G Adventures</>,
    speakers: ""
  },
  {
    episode: "7",
    name: "A Fireside Chat with Mike Premo and Dave Hilfman",
    description: "asdf",
    embedUrl: "fkU55zhJDXk",
    link: "/episodes/A-Fireside-Chat-with-Mike-Premo-and-Dave-Hilfman/",
    time: "3:00 p.m. EST",
    date: "Dec 15, 2020",
    cta: "View Details",
    tags: "Innovation",
    title: <>Exploring the Future of Travel with G Adventures</>,
    speakers: "",
  },
  {
    episode: "8",
    name: "Exploring the Future of Travel with G Adventures",
    description: "asdf",
    embedUrl: "rSen3jbg_Z4",
    link: "/episodes/exploring-the-future-of-travel-with-g-adventures/",
    time: "Available Now",
    date: "Feb 18, 2021",
    cta: "View Details",
    tags: "Data and Trends, Innovation",
    title: <>Exploring the Future of Travel with G Adventures</>,
    speakers: "",
  },
  {
    episode: "9",
    name: "Assessing the Travel Industry with A4A",
    description: "asdf",
    embedUrl: "XdyDmdQnLvo",
    link: "/episodes/Assessing-the-Travel-Industry-with-A4A/",
    time: "Available Now",
    date: "Apr 28, 2021",
    cta: "View Details",
    tags: "Retailing, Innovation",
    title: <>Exploring the Future of Travel with G Adventures</>,
    speakers: "",
  },
  {
    episode: "10",
    name: "Southwest Business Talks Distribution, Industry Recovery",
    description: "asdf",
    embedUrl: "f5lhm-ur0p8",
    link: "/episodes/southwest-business-talks-distribution-industry-recovery/",
    time: "Available Now",
    date: "May 13, 2021",
    cta: "View Details",
    tags: "Retailing",
    title: <>Exploring the Future of Travel with G Adventures</>,
    speakers: "",
  },
  {
    episode: "11",
    name: "Distribution, Recovery and Collaboration with American Airlines",
    description: "asdf",
    embedUrl: "BmL6X6Akdzw",
    link: "/episodes/distribution-recovery-collaboration-american-airlines/",
    time: "Available Now",
    date: "June 29, 2021",
    cta: "View Details",
    tags: "Retailing, Innovation",
    title: <>Exploring the Future of Travel with G Adventures</>,
    speakers: "",
  },
  {
    episode: "12",
    name: "Hopper on the Value of Fintech in Travel",
    description: "asdf",
    embedUrl: "EtC9bJPwqV8",
    link: "/episodes/hopper-on-value-of-fintech-in-travel/",
    time: "Available Now",
    date: "July 22, 2021",
    cta: "View Details",
    tags: "Data and Trends",
    title: <>Exploring the Future of Travel with G Adventures</>,
    speakers: "",
  },
  {
    episode: "13",
    name: "The Realities of Omnichannel Retailing",
    description: "asdf",
    embedUrl: "T4f-Lz3tuls",
    link: "/episodes/the-realities-of-omnichannel-retailing/",
    time: "Available Now",
    date: "October 20, 2021",
    cta: "View Details",
    tags: "Retailing",
    title: <>Exploring the Future of Travel with G Adventures</>,
    speakers: "",
  },
  {
    episode: "14",
    name: "Using Consumer Spending to Track Travel Trends",
    description: "asdf",
    embedUrl: "O_xWge5uN5A",
    link: "/episodes/using-consumer-spending-to-track-travel-trends/",
    time: "Available Now",
    date: "February 24, 2022",
    cta: "View Details",
    tags: "Data and Trends",
    title: <>Exploring the Future of Travel with G Adventures</>,
    speakers: "",
  },
  {
    episode: "15",
    name: "Growth and Innovation at the Denver Airport",
    description: "asdf",
    embedUrl: "ylBV3q8-5IM",
    link: "/episodes/growth-and-innovation-at-the-denver-airport/",
    time: "Available Now",
    date: "June 23, 2022",
    cta: "View Details",
    tags: "Innovation",
    title: <>Exploring the Future of Travel with G Adventures</>,
    speakers: "",
  },
];
