export const episodes = [
 
  {
    episode: "1",
    name: "2020 Outlook: Travel Recovery Trends to Watch",
    description: "asdf",
    embedUrl: "https://www.youtube.com/watch?v=93hQquGY4fs",
    link: "/episodes/2020-outlook-travel-recovery-trends-to-watch/",
    time: "Available Now",
    date: "June 4, 2020",
    cta: "View Details",
    tags: "Data and Trends",
  },
  {
    episode: "2",
    name: "How Travel Systems are Adapting to COVID-19",
    description: "asdf",
    embedUrl: "https://www.youtube.com/watch?v=lEy5UakXXmI",
    link: "/episodes/How-Travel-System-are-Adapting-to-COVID-19/",
    time: "Available Now",
    date: "July 27, 2020",
    cta: "View Details",
    tags: "Innovation",
  },
  {
    episode: "3",
    name: "What’s Next for Business Travel?",
    description: "asdf",
    embedUrl: "https://www.youtube.com/watch?v=1mam8X5N_l0",
    link: "/episodes/Whats-Next-for-Business-Travel/",
    time: "Available Now",
    date: "August 19, 2020",
    cta: "View Details",
    tags: "Retailing, Innovation",
  },
  {
    episode: "4",
    name: "What’s Really on the Dark Web?",
    description: "asdf",
    embedUrl:"https://www.youtube.com/watch?v=laZMBVj9ZbM",
    link: "/episodes/Whats-Really-on-the-Dark-Web/",
    time: "Available Now",
    date: "September 17, 2020",
    cta: "View Details",
    tags: "Data and Trends",
  },
  {
    episode: "5",
    name: "Travel Recovery Trends to Watch in Fall 2020",
    description: "asdf",
    embedUrl: "https://www.youtube.com/watch?v=oN1LocEIPVg",
    link: "/episodes/Travel-Recovery-Trends-to-Watch-in-Fall-2020/",
    time: "Available Now",
    date: "October 14, 2020",
    cta: "View Details",
    tags: "Data and Trends",
  },
  {
    episode: "6",
    name: "Enhancing the Traveler Experience in Every Channel",
    description: "asdf",
    embedUrl: "https://www.youtube.com/watch?v=uE9RtodEpSc",
    link: "/episodes/Enhancing-the-Traveler-Experience-in-Every-Channel/",
    time: "Available Now",
    date: "Nov 18, 2020",
    cta: "View Details",
    tags: "Retailing, Innovation",
  },
  {
    episode: "7",
    name: "A Fireside Chat with Mike Premo and Dave Hilfman",
    description: "asdf",
    embedUrl: "https://www.youtube.com/watch?v=fkU55zhJDXk",
    link: "/episodes/A-Fireside-Chat-with-Mike-Premo-and-Dave-Hilfman/",
    time: "3:00 p.m. EST",
    date: "Dec 15, 2020",
    cta: "View Details",
    tags: "Innovation",
  }, 
  {
    episode: "8",
    name: "Exploring the Future of Travel with G Adventures",
    description: "asdf",
    embedUrl: "https://www.youtube.com/watch?v=rSen3jbg_Z4",
    link: "/episodes/exploring-the-future-of-travel-with-g-adventures/",
    time: "Available Now",
    date: "Feb 18, 2021",
    cta: "View Details",
    tags: "Data and Trends, Innovation",
  },
  {
    episode: "9",
    name: "Assessing the Travel Industry with A4A",
    description: "asdf",
    embedUrl: "https://www.youtube.com/watch?v=XdyDmdQnLvo",
    link: "/episodes/Assessing-the-Travel-Industry-with-A4A/",
    time: "Available Now",
    date: "Apr 28, 2021",
    cta: "View Details",
    tags: "Retailing, Innovation",
  },
  {
    episode: "10",
    name: "Southwest Business Talks Distribution, Industry Recovery",
    description: "asdf",
    embedUrl: "https://www.youtube.com/watch?v=f5lhm-ur0p8",
    link: "/episodes/southwest-business-talks-distribution-industry-recovery/",
    time: "Available Now",
    date: "May 13, 2021",
    cta: "View Details",
    tags: "Retailing",
  },
  {
    episode: "11",
    name: "Distribution, Recovery and Collaboration with American Airlines",
    description: "asdf",
    embedUrl: "https://www.youtube.com/watch?v=BmL6X6Akdzw",
    link: "/episodes/distribution-recovery-collaboration-american-airlines/",
    time: "Available Now",
    date: "June 29, 2021",
    cta: "View Details",
    tags: "Retailing, Innovation",
  },
  {
    episode: "12",
    name: "Hopper on the Value of Fintech in Travel",
    description: "asdf",
    embedUrl: "https://www.youtube.com/watch?v=EtC9bJPwqV8",
    link: "/episodes/hopper-on-value-of-fintech-in-travel/",
    time: "Available Now",
    date: "July 22, 2021",
    cta: "View Details",
    tags: "Data and Trends",
  },
  {
    episode: "13",
    name: "The Realities of Omnichannel Retailing",
    description: "asdf",
    embedUrl: "https://www.youtube.com/watch?v=T4f-Lz3tuls",
    link: "/episodes/the-realities-of-omnichannel-retailing/",
    time: "Available Now",
    date: "October 20, 2021",
    cta: "View Details",
    tags: "Retailing",
  },
  {
    episode: "14",
    name: "Using Consumer Spending to Track Travel Trends",
    description: "asdf",
    embedUrl: "https://www.youtube.com/watch?v=O_xWge5uN5A",
    link: "/episodes/using-consumer-spending-to-track-travel-trends/",
    time: "Available Now",
    date: "February 24, 2022",
    cta: "View Details",
    tags: "Data and Trends",
  },
  {
    episode: "15",
    name: "Growth and Innovation at the Denver Airport",
    description: "asdf",
    embedUrl: "https://www.youtube.com/watch?v=ylBV3q8-5IM",
    link: "/episodes/growth-and-innovation-at-the-denver-airport/",
    time: "Available Now",
    date: "June 23, 2022",
    cta: "View Details",
    tags: "Innovation",
  },
];

export const episodeData = [
  {
    id: 1,
    title: <>2020 Outlook: Travel Recovery Trends to Watch</>,
    description: "",
    url: "/episodes/2020-outlook-travel-recovery-trends-to-watch/",
    embedUrl: "/episodes/2020-outlook-travel-recovery-trends-to-watch/",
    tag: "",
    date: "June 4, 2020",
  },
  {
    id: 15,
    title: (
      <>
        Growth and Innovation at the <br />
        Denver International Airport
      </>
    ),
    description: "",
    embedUrl: "",
    tag: "",
    date: "",
  },
];